baseURL = "http://cashpw.com/"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en-us"
theme = "PaperMod"
title = "Cash Prokop-Weaver"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
DateFormat = "2006-01-02"
author = "Cash Prokop-Weaver"
defaultTheme = "dark"
description = "Personal website"
env = "production"

[params.profileMode]
enabled = true
title = "Hi there 🎉"
subtitle = """I work as a software engineer, potter, and photographer. <a href=\"mailto:cash@cashpw.com\">Get in touch</a>!"""

[[params.socialIcons]]
name = "email"
url = "mailto:cash@cashpw.com"

[[params.socialIcons]]
name = "github"
url = "https://github.com/cashpw"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/cashpw"

[markup.goldmark.renderer]
unsafe = true
